Milestone 3 Tutorial 2
AgregoreWeb/website pull request #50
Opened 2023-12-12 10:14 UTC by dirkcuys

This PR contains
- the tutorial for uploading a directory of files to IPFS
- an updated development environment bootstrap that can be used to create IPFS sites in Agregore Web
- a retrospective on the creation of the functionality and tutorial

2023-12-19 20:03 UTC, RangerMauve requested changes

2023-12-19 20:14 UTC, RangerMauve commented
Mind moving the retrospective into the blog folder?

2023-12-19 23:15 UTC, dirkcuys commented on docs/tutorials/ipfs-dir-upload/index.md
> +We will be using a [self-hosted development environment](https://agregore.mauve.moe/docs/examples/browser-devenv/) for Agregore that we created in a [previous tutorial](https://agregore.mauve.moe/doc
makes sense, will do

2023-12-19 23:24 UTC, dirkcuys commented on docs/examples/browser-devenv-v2/files/style.css
> +    font-family: var(--ag-theme-font-family);
I think I did try that, but the styles for the editor didn't work well with the defaults and I haven't gotten around to fix that. If it's fine with you, I'd rather change this in the next tutorial

2023-12-19 23:39 UTC, dirkcuys commented
I moved the retrospective and updated the structure a bit. I like what @tripledoublev did with it.

2024-01-09 14:49 UTC, RangerMauve approved these changes

2024-01-09 14:51 UTC, merged