Fix p2pad hyper drive key by renaming parameter in generateHyperdriveKey
AgregoreWeb/website pull request #67
Opened 2024-11-13 19:06 UTC by akhileshthite

![Screenshot 2024-11-13 at 10 56 16 AM](https://github.com/user-attachments/assets/ed259621-98f9-4f1f-b90e-0360af21302a)
![Screenshot 2024-11-13 at 10 56 53 AM](https://github.com/user-attachments/assets/3c8f9cae-ac08-4236-a963-e818eaf10bc4)

2024-11-14 16:58 UTC, RangerMauve requested changes
👍

2024-11-14 17:53 UTC, akhileshthite commented on explore.md
> +### Extensions:
Oh yes, I think it's because the old branch.

2024-11-15 00:03 UTC, RangerMauve approved these changes

2024-11-15 00:03 UTC, merged

2024-11-15 00:03 UTC, RangerMauve commented
Perf, ty!